### ISSUE TITLE
Loomo ROS has stopped

### ISSUE THREAD

**Issue by Wanja1204** [mit-acl/android_loomo_ros_core#1] opened 2019-09-13 05:55 UTC
Hello, thank you for sharing your knowledge. I have a problem if the cameras in the app are turned on automatically, the app will stop with the message (Unfortunately, Loomo ROS has stopped)

**Comment by mfe7** [comment] 2019-09-16 00:10
If you disable the cameras from turning on automatically, does it still
crash? I didn’t put any debug/error msgs or exception catching
unfortunately. So I’m wondering if the problem is definitely isolated to
the cameras. Another thing I’m unsure of is if any of the API has changed
for names/functions since it’s been several months since I tried this out

**Comment by mfe7** [comment] 2020-02-03 22:49
@Wanja1204 we've released an updated version of this code and a binary file. Unsure if it addresses your issue, but I will close this and feel free to re-open if your issue persists.

**Closed as completed by mfe7** 2020-02-03 22:49 UTC
